In [1]:
import numpy as np
from System import *

In [2]:

gr = System([20,20,1],"shells2D")
print(gr.onSiteAnisotropies)
gr.update()


FeA 1 1 from file  FM2D.matshell


0

In [3]:
for i in range(100):
    gr.update()
print(gr.grid)

[[[[ 0.7116542   0.34988837  0.60920146]]

  [[ 0.6491084   0.30897437  0.69512094]]

  [[ 0.64422385  0.76422116 -0.03068635]]

  ...

  [[ 0.41313557  0.8927235   0.17989931]]

  [[ 0.10096053  0.60894149  0.78676377]]

  [[ 0.71853509  0.66742648  0.19557406]]]


 [[[ 0.43562991  0.72368858  0.53525827]]

  [[ 0.11209066  0.72916915  0.67509114]]

  [[ 0.73904747  0.04783741  0.67195269]]

  ...

  [[ 0.26944255  0.96273156  0.0234234 ]]

  [[ 0.44325166  0.65181608  0.61535661]]

  [[ 0.92214509 -0.01223087  0.38665079]]]


 [[[ 0.89392504  0.15004783  0.42235491]]

  [[ 0.27417849  0.81837081  0.50506967]]

  [[ 0.80478062  0.41469589  0.42468279]]

  ...

  [[ 0.03193347  0.7163946   0.69696415]]

  [[ 0.73978856  0.6131837   0.27698127]]

  [[ 0.37581368  0.66577197  0.64460202]]]


 ...


 [[[ 0.64244624  0.4620685   0.61135549]]

  [[ 0.81758384  0.36408174  0.44609545]]

  [[ 0.65607502  0.19913571  0.72794955]]

  ...

  [[ 0.00747097  0.07990575  0.99677443]]

  [[ 0.748289